RANDOM_SEED=42
# DUSHA
SPEAKER_EMOTION_FIELD_NAME = 'speaker_emo'
ANNOTATOR_EMOION_FIELD_NAME = 'annotator_emo'
GOLDEN_EMOTION_FIELD_NAME = 'golden_emo'
SPEAKER_TEXT_FIELD_NAME = 'speaker_text'

# TEXT_2_EMOTION MODEL
TEXT_2_EMOTION_FEATURE_FIELD_NAME = SPEAKER_TEXT_FIELD_NAME
TEXT_2_EMOTION_TARGET_FIELD_NAME = SPEAKER_EMOTION_FIELD_NAME
TRAIN_PART_SIZE:int = int(2e5)
TEST_PART_SIZE:int = int(TRAIN_PART_SIZE * 0.2)

# METRICS
PREDICTIONS_COL_NAME:str = 'pred'
TRUE_COL_NAME:str = 'true'