from pathlib import Path
import sys

sys.path.append('..')
from configs.base import (
    DOT,
    CSV,
    PT,
)

PROJECT_DATA_DIR_PATH = Path('/data01/vvkiselev/data/other/dpl')
TRAIN_DIR_NAME:str = 'train'
TEST_DIR_NAME:str = 'test'

# Dusha
DUSHA_DIR_NAME:str = 'dusha'
DUSHA_DIR_PATH:Path = PROJECT_DATA_DIR_PATH / DUSHA_DIR_NAME
CROWD_DIR_NAME:str = 'crowd'
DUSHA_CROWD_DIR_PATH:Path = DUSHA_DIR_PATH / CROWD_DIR_NAME
DUSHA_WAVS_DIR_NAME:str = 'wavs'
DUSHA_CROWD_TRAIN_DIR_PATH:Path = DUSHA_CROWD_DIR_PATH / 'crowd_train'
DUSHA_CROWD_TRAIN_FILE_PATH:Path = DUSHA_CROWD_TRAIN_DIR_PATH/ 'raw_crowd_train.tsv'
DUSHA_CROWD_TRAIN_WAVS_DIR_PATH:Path = DUSHA_CROWD_TRAIN_DIR_PATH / DUSHA_WAVS_DIR_NAME
DUSHA_CROWD_TEST_DIR_PATH:Path = DUSHA_CROWD_DIR_PATH / 'crowd_test'
DUSHA_CROWD_TEST_FILE_PATH:Path = DUSHA_CROWD_TEST_DIR_PATH / 'raw_crowd_test.tsv'
DUSHA_CROWD_TEST_WAVS_DIR_PATH:Path = DUSHA_CROWD_TEST_DIR_PATH / DUSHA_WAVS_DIR_NAME

# Processed
PROCESSED_DIR_PATH:Path = PROJECT_DATA_DIR_PATH / 'processed'
PROCESSED_DUSHA_DIR_PATH:Path = PROCESSED_DIR_PATH / DUSHA_DIR_NAME
PROCESSED_DUSHA_CROWD_DIR_PATH:Path = PROCESSED_DUSHA_DIR_PATH / CROWD_DIR_NAME
PROCESSED_DUSHA_CROWD_TRAIN_DIR_PATH:Path = PROCESSED_DUSHA_CROWD_DIR_PATH / TRAIN_DIR_NAME
PROCESSED_DUSHA_CROWD_TEST_DIR_PATH:Path = PROCESSED_DUSHA_CROWD_DIR_PATH / TEST_DIR_NAME
HLF_DIR_NAME:str = 'HLF'
PROCESSED_DUSHA_CROWD_TRAIN_HLF_DIR_PATH:Path = PROCESSED_DUSHA_CROWD_TRAIN_DIR_PATH / HLF_DIR_NAME
PROCESSED_DUSHA_CROWD_TEST_HLF_DIR_PATH:Path = PROCESSED_DUSHA_CROWD_TEST_DIR_PATH / HLF_DIR_NAME
HLF_LAST_VERSION_FILE_NAME:str = 'v1' + DOT + CSV
PROCESSED_DUSHA_CROWD_TRAIN_HLF_LAST_VERSION_FILE_PATH:Path = PROCESSED_DUSHA_CROWD_TRAIN_HLF_DIR_PATH / HLF_LAST_VERSION_FILE_NAME
PROCESSED_DUSHA_CROWD_TEST_HLF_LAST_VERSION_FILE_PATH:Path = PROCESSED_DUSHA_CROWD_TEST_HLF_DIR_PATH / HLF_LAST_VERSION_FILE_NAME

TEXT_EMBEDDING_DIR_NAME:str = 'text_embeddings'
PROCESSED_DUSHA_CROWD_TRAIN_TEXT_EMBEDDINGS_DIR_PATH:Path = PROCESSED_DUSHA_CROWD_TRAIN_DIR_PATH / TEXT_EMBEDDING_DIR_NAME
PROCESSED_DUSHA_CROWD_TEST_TEXT_EMBEDDINGS_DIR_PATH:Path = PROCESSED_DUSHA_CROWD_TEST_DIR_PATH / TEXT_EMBEDDING_DIR_NAME
TEXT_EMBEDDINGS_LAST_VERSION_FILE_NAME:str = 'v1' + DOT + PT
PROCESSED_DUSHA_CROWD_TRAIN_TEXT_EMBEDDINGS_LAST_VERSION_FILE_PATH:Path = PROCESSED_DUSHA_CROWD_TRAIN_TEXT_EMBEDDINGS_DIR_PATH / TEXT_EMBEDDINGS_LAST_VERSION_FILE_NAME
PROCESSED_DUSHA_CROWD_TEST_TEXT_EMBEDDINGS_LAST_VERSION_FILE_PATH:Path = PROCESSED_DUSHA_CROWD_TEST_TEXT_EMBEDDINGS_DIR_PATH / TEXT_EMBEDDINGS_LAST_VERSION_FILE_NAME


# Models
MODELS_DIR_PATH:Path = PROJECT_DATA_DIR_PATH / 'models'
WHISPER_MEDIUM_DIR_PATH:Path = MODELS_DIR_PATH / 'whisper_medium' 

def crowd_test_wav_path_2_abs_path(
    path:str,
    crowd_test_path:Path = DUSHA_CROWD_TEST_DIR_PATH,
    )->Path:
    return crowd_test_path  / path

